name: Musser Scout Reservation
title: Musser Scout Reservation
logo: "/img/logo.png"
description: "The Musser camping experience includes a variety of program ventures including Cub summer camp options, exciting year-round programs, and diverse training courses for Scouts and Scouters of all ages."

alert:
  text: <a href="/coronavirus">Click here for an important update about 2020 Cub Scout Summer Camps</a><br>For the safety of our members, Cradle of Liberty Council-level events and camps will be closed <strong>as we continue to evaluate state regulations for reopening.</strong><br>For the latest updates regarding council events and camps, please visit <a href="http://colbsa.org/coronavirus">colbsa.org/coronavirus</a>.
  class: alert-danger

plugins:
  - jekyll-paginate-v2
  - jekyll_picture_tag
  - jekyll/minibundle
  - jekyll-contentblocks

url: http://127.0.0.1:4000
baseurl:

picture:
  nomarkdown: false
  suppress_warnings: true

recaptcha: 6LdmHcIUAAAAAMMBaaQiAMhIn25IwZQC7Xeb2byD

permalink: /news/:title

pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: 'News - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
